FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD ClothingWebsite.jar /opt/ClothingWebsite/
EXPOSE 8080
WORKDIR /opt/ClothingWebsite/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "ClothingWebsite.jar"]
